from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from .engine import CreationEngine
from .automation import DailyAutomationScheduler, DailyAutomationService, DailyScheduleConfig
from .generation import GenerationProviderRegistry, GenerationRouteConfig, GenerationRouter
from .models import MusicCreationRequest, RightsConfiguration
from .repository import ResultRepository, result_from_dict
from .skills import skills_snapshot


def load_request(path: str) -> MusicCreationRequest:
    with Path(path).open("r", encoding="utf-8") as handle:
        data: dict[str, Any] = json.load(handle)
    return MusicCreationRequest(**data)


def build_generation_router(args: argparse.Namespace) -> GenerationRouter:
    provider = getattr(args, "generation_provider", None)
    if not provider:
        return GenerationRouter.from_env()
    command_json = getattr(args, "local_command_json", "[]")
    if command_json.startswith("@"):
        command_json = Path(command_json[1:]).read_text(encoding="utf-8-sig")
    command = tuple(json.loads(command_json)) if command_json else ()
    return GenerationRouter(
        GenerationRouteConfig(
            provider=provider,
            model_name=getattr(args, "model_name", None) or ("mock_sine_arranger" if provider == "mock" else provider),
            model_version=getattr(args, "model_version", None) or "0.1.0",
            command=command,
            timeout_sec=getattr(args, "generation_timeout", 120),
        )
    )


def build_engine(output: str, args: argparse.Namespace) -> CreationEngine:
    provider_config = getattr(args, "provider_config", None)
    if provider_config:
        return CreationEngine(
            output,
            provider_registry=GenerationProviderRegistry.from_file(provider_config),
            preferred_provider_id=getattr(args, "preferred_provider", None),
        )
    return CreationEngine(output, generation_router=build_generation_router(args))


def summarize(result, selected) -> dict[str, object]:
    return {
        "task_id": result.task_id,
        "work_id": result.work_id,
        "selected_version_id": result.selected_version_id,
        "rights_status": result.rights_status,
        "qa_summary": result.qa_summary,
        "downloadable_files": [
            export.path or export.download_url
            for export in selected.export_files
            if export.ready and (export.path or export.download_url)
        ],
    }


def maybe_configure_rights(engine: CreationEngine, result, enabled: bool, args: argparse.Namespace | None = None):
    if not enabled:
        return result
    return engine.configure_rights(
        result,
        RightsConfiguration(
            rights_owner="Internal AI Music Lab",
            usage_scope="internal demo and production validation",
            territory="worldwide",
            duration="perpetual",
            ai_disclosure="Generated by AI music production engine MVP with human-directed prompt and QA.",
            model_license="internal mock generator; replace with real model license before commercial delivery",
            commercial_use_allowed=False,
            platform_profile_id=getattr(args, "platform_profile_id", None) or "internal_export",
            export_profile=getattr(args, "export_profile", None) or "wav_master_preview_license",
            manual_approval_required=bool(getattr(args, "manual_approval_required", False)),
            notes="Demo rights config only.",
        ),
    )


def maybe_package(engine: CreationEngine, result, enabled: bool):
    if enabled:
        engine.create_delivery_package(result)
    return result


def demo(args: argparse.Namespace) -> None:
    engine = build_engine(args.output, args)
    request = MusicCreationRequest(
        title="自动创作测试曲",
        mode="song",
        language="zh",
        theme="凌晨城市里的希望",
        mood=["warm", "hopeful", "cinematic"],
        genre=["pop", "electronic"],
        audience="short video creators and indie music listeners",
        use_case="AI music production MVP validation",
        duration_sec=args.duration,
        bpm=104,
        key="C",
        vocal_required=True,
        forbidden=["real singer imitation", "existing song melody copy"],
        export_formats=["wav"],
    )
    result = engine.create(request, candidate_count=3)
    result = maybe_configure_rights(engine, result, args.configure_rights, args)
    result = maybe_package(engine, result, args.package)
    selected = next(version for version in result.versions if version.version_id == result.selected_version_id)
    export_root = Path(args.output) / result.task_id / "exports"
    trim_export = engine.render_trim(selected, 0, min(15, selected.duration_sec), export_root / f"{selected.version_id}_15s.wav")
    fade_export = engine.render_fade(selected, 0.5, 1.0, export_root / f"{selected.version_id}_fade.wav")
    loop_export = engine.render_loop(selected, min(30, max(5, selected.duration_sec)), export_root / f"{selected.version_id}_loop.wav")
    selected.export_files.extend([trim_export, fade_export, loop_export])

    print(json.dumps(summarize(result, selected), ensure_ascii=False, indent=2))


def create(args: argparse.Namespace) -> None:
    engine = build_engine(args.output, args)
    request = load_request(args.request)
    result = engine.create(request, candidate_count=args.candidates)
    result = maybe_configure_rights(engine, result, args.configure_rights, args)
    result = maybe_package(engine, result, args.package)
    selected = next(version for version in result.versions if version.version_id == result.selected_version_id)
    print(json.dumps(summarize(result, selected), ensure_ascii=False, indent=2))


def import_url(args: argparse.Namespace) -> None:
    engine = build_engine(args.output, args)
    request = load_request(args.request)
    result = engine.import_external_download(
        request,
        download_url=args.url,
        duration_sec=args.duration,
        candidate_count=args.candidates,
    )
    result = maybe_configure_rights(engine, result, args.configure_rights, args)
    result = maybe_package(engine, result, args.package)
    selected = next(version for version in result.versions if version.version_id == result.selected_version_id)
    print(json.dumps(summarize(result, selected), ensure_ascii=False, indent=2))


def daily(args: argparse.Namespace) -> None:
    provider_config = getattr(args, "provider_config", None)
    registry = GenerationProviderRegistry.from_file(provider_config) if provider_config else None
    service = DailyAutomationService(args.output, provider_registry=registry, preferred_provider_id=getattr(args, "preferred_provider", None))
    report = service.create_daily_batch(target_count=args.count, candidate_count=args.candidates)
    print(json.dumps(report, ensure_ascii=False, indent=2))


def rework(args: argparse.Namespace) -> None:
    service = DailyAutomationService(args.output)
    report = service.run_rework_queue(limit=args.limit)
    print(json.dumps(report, ensure_ascii=False, indent=2))


def schedule(args: argparse.Namespace) -> None:
    provider_config = getattr(args, "provider_config", None)
    registry = GenerationProviderRegistry.from_file(provider_config) if provider_config else None
    scheduler = DailyAutomationScheduler(
        args.output,
        config=DailyScheduleConfig(
            target_count=args.count,
            candidate_count=args.candidates,
            rework_limit=args.rework_limit,
            run_hour=args.run_hour,
            run_minute=args.run_minute,
        ),
        provider_registry=registry,
        preferred_provider_id=getattr(args, "preferred_provider", None),
    )
    now = datetime.fromisoformat(args.now) if args.now else None
    report = scheduler.run_due(now=now)
    print(json.dumps(report, ensure_ascii=False, indent=2))


def skills(_: argparse.Namespace) -> None:
    print(json.dumps(skills_snapshot(), ensure_ascii=False, indent=2))


def package(args: argparse.Namespace) -> None:
    repository = ResultRepository(args.output)
    data = repository.get_result(args.task_id)
    if data is None:
        raise SystemExit(f"task not found: {args.task_id}")
    engine = CreationEngine(args.output)
    result = result_from_dict(data)
    export = engine.create_delivery_package(result, selected_version_id=args.version_id)
    print(json.dumps({"task_id": result.task_id, "version_id": export.version_id, "delivery_package": export.path}, ensure_ascii=False, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description="AI music creation engine")
    subparsers = parser.add_subparsers(required=True)

    def add_generation_args(target: argparse.ArgumentParser) -> None:
        target.add_argument("--generation-provider", choices=["mock", "local_command"], default=None, help="Generation provider; defaults to env or mock")
        target.add_argument("--local-command-json", default="[]", help="JSON array command template for local_command provider; use @path to read from file")
        target.add_argument("--model-name", default=None, help="Model name to record in generation metadata")
        target.add_argument("--model-version", default=None, help="Model version to record in generation metadata")
        target.add_argument("--generation-timeout", type=int, default=120, help="Generation timeout in seconds")
        target.add_argument("--provider-config", default=None, help="Provider capability config JSON; overrides single-provider flags")
        target.add_argument("--preferred-provider", default=None, help="Provider id to force from provider config if it can handle the request")

    def add_rights_args(target: argparse.ArgumentParser) -> None:
        target.add_argument("--platform-profile-id", default="internal_export", help="Delivery platform/profile id recorded in license and manifest")
        target.add_argument("--export-profile", default="wav_master_preview_license", help="Delivery export profile recorded in license and manifest")
        target.add_argument("--manual-approval-required", action="store_true", help="Mark delivery package as requiring manual approval")

    demo_parser = subparsers.add_parser("demo", help="Run a Phase 1 creation engine demo")
    demo_parser.add_argument("--output", default="runs", help="Output workspace")
    demo_parser.add_argument("--duration", type=int, default=20, help="Generated mock audio duration in seconds")
    demo_parser.add_argument("--configure-rights", action="store_true", help="Create a demo license pack and unblock master exports")
    demo_parser.add_argument("--package", action="store_true", help="Create a delivery package after rights are configured")
    add_generation_args(demo_parser)
    add_rights_args(demo_parser)
    demo_parser.set_defaults(func=demo)

    create_parser = subparsers.add_parser("create", help="Create music from a JSON request")
    create_parser.add_argument("--request", required=True, help="Path to MusicCreationRequest JSON")
    create_parser.add_argument("--output", default="runs", help="Output workspace")
    create_parser.add_argument("--candidates", type=int, default=3, help="Candidate count, 3-5")
    create_parser.add_argument("--configure-rights", action="store_true", help="Create a demo license pack and unblock master exports")
    create_parser.add_argument("--package", action="store_true", help="Create a delivery package after rights are configured")
    add_generation_args(create_parser)
    add_rights_args(create_parser)
    create_parser.set_defaults(func=create)

    import_parser = subparsers.add_parser("import-url", help="Register an externally generated AI music download URL")
    import_parser.add_argument("--request", required=True, help="Path to MusicCreationRequest JSON")
    import_parser.add_argument("--url", required=True, help="External generated music download URL")
    import_parser.add_argument("--duration", type=float, required=True, help="External audio duration in seconds")
    import_parser.add_argument("--output", default="runs", help="Output workspace")
    import_parser.add_argument("--candidates", type=int, default=3, help="Candidate count, 3-5")
    import_parser.add_argument("--configure-rights", action="store_true", help="Create a demo license pack and unblock master exports")
    import_parser.add_argument("--package", action="store_true", help="Create a delivery package after rights are configured")
    add_generation_args(import_parser)
    add_rights_args(import_parser)
    import_parser.set_defaults(func=import_url)

    daily_parser = subparsers.add_parser("daily", help="Create an automated daily production batch")
    daily_parser.add_argument("--output", default="runs", help="Output workspace")
    daily_parser.add_argument("--count", type=int, default=10, help="Daily task count, 10-20")
    daily_parser.add_argument("--candidates", type=int, default=3, help="Candidates per task, 3-5")
    add_generation_args(daily_parser)
    daily_parser.set_defaults(func=daily)

    rework_parser = subparsers.add_parser("rework", help="Run targeted rework for queued failures")
    rework_parser.add_argument("--output", default="runs", help="Output workspace")
    rework_parser.add_argument("--limit", type=int, default=5, help="Maximum rework items to process")
    rework_parser.set_defaults(func=rework)

    schedule_parser = subparsers.add_parser("schedule", help="Run the daily automation scheduler once if due")
    schedule_parser.add_argument("--output", default="runs", help="Output workspace")
    schedule_parser.add_argument("--count", type=int, default=10, help="Daily task count, 10-20")
    schedule_parser.add_argument("--candidates", type=int, default=3, help="Candidates per task, 3-5")
    schedule_parser.add_argument("--rework-limit", type=int, default=5, help="Maximum rework items to process after daily generation")
    schedule_parser.add_argument("--run-hour", type=int, default=0, help="Scheduled local hour, 0-23")
    schedule_parser.add_argument("--run-minute", type=int, default=0, help="Scheduled local minute, 0-59")
    schedule_parser.add_argument("--now", default=None, help="Override current time as ISO datetime for validation")
    add_generation_args(schedule_parser)
    schedule_parser.set_defaults(func=schedule)

    skills_parser = subparsers.add_parser("skills", help="Print project foundation skills, agents, and rework rules")
    skills_parser.set_defaults(func=skills)

    package_parser = subparsers.add_parser("package", help="Create a delivery package for an existing authorized task")
    package_parser.add_argument("--output", default="runs", help="Output workspace")
    package_parser.add_argument("--task-id", required=True, help="Task id to package")
    package_parser.add_argument("--version-id", default=None, help="Version id to package; defaults to selected version")
    package_parser.set_defaults(func=package)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
